### ISSUE TITLE
An error is coming on the variable product with the WooCommerce Stripe Gateway plugin as active.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-call-for-price#34]
**Describe the bug**
An error is coming on the variable product with the WooCommerce Stripe Gateway plugin as active.

CRITICAL Uncaught Error: Call to a member function get_id() on string in /www/westlakeprocom_613/public/wp-content/plugins/woocommerce-call-for-price/includes/class-wc-call-for-price.php:255
Stack trace:
#0 /www/westlakeprocom_613/public/wp-includes/class-wp-hook.php(303): Alg_WC_Call_For_Price->alg_cfp_empty_price_products_stock_management('')
#1 /www/westlakeprocom_613/public/wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array)
#2 /www/westlakeprocom_613/public/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php(1091): apply_filters('woocommerce_sho...', '')
#3 /www/westlakeprocom_613/public/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(384): wc_format_content('')
#4 /www/westlakeprocom_613/public/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(312): WC_Product_Variable->get_available_variation(Object(WC_Product_Variation))
#5 /www/westlakeprocom_613/public/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-pa in /www/westlakeprocom_613/public/wp-content/plugins/woocommerce-call-for-price/includes/class-wc-call-for-price.php on line 255

**To Reproduce**
1. Install and activate the WooCommerce Stripe Gateway plugin. https://wordpress.org/plugins/woocommerce-gateway-stripe/
2. Then, visit the variable product page. You will be able to see the above error there.

**Expected behavior**
Such an error should not come.

**Screenshots**

**Additional context**
https://wordpress.org/support/topic/call-for-price-plugin-causing-error-pages-on-variable-products/#post-15147436
https://tychesoftwares.freshdesk.com/a/tickets/36369

**Comment by priyanka-tychesoftwares** [comment]
Another client facing this same issue: https://wordpress.org/support/topic/scarsa-funzionalita/

**Comment by priyanka-tychesoftwares** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/39344
